public class Comentarios {

public static void main (String[] args){

    // Public = Refere a visibilidade do metodo
    // Static = Refere a propriedade da classe
    // Void = Refere ao metodo sem retono, (nenhum valor)
    // Main = É o nome do metodo de execução de toda a aplicação
    // String[] args é o valor de string do Java ! 


    Sistem.out.println("Testando os comentarios");

    

}




}